# Generated by Django 4.2.7 on 2025-07-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_contactmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        default="website",
                        help_text="Where they signed up",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Subscription",
                "verbose_name_plural": "Newsletter Subscriptions",
                "ordering": ["-subscribed_at"],
            },
        ),
    ]
