# Generated by Django 4.2.7 on 2025-07-31 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="book_authors",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="book_title",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
